-- Indexes for the access paths the application actually uses: every business query is scoped by company and most filter or
-- sort by date; child rows are always fetched by their parent. (Unique constraints already index company+number and the like.)
CREATE INDEX IF NOT EXISTS idx_parties_company_type ON parties (company_id, type);
CREATE INDEX IF NOT EXISTS idx_items_company ON items (company_id);
CREATE INDEX IF NOT EXISTS idx_invoices_company_date ON invoices (company_id, date);
CREATE INDEX IF NOT EXISTS idx_invoices_party ON invoices (party_id);
CREATE INDEX IF NOT EXISTS idx_invoice_lines_invoice ON invoice_lines (invoice_id);
CREATE INDEX IF NOT EXISTS idx_purchases_company_date ON purchases (company_id, date);
CREATE INDEX IF NOT EXISTS idx_purchases_party ON purchases (party_id);
CREATE INDEX IF NOT EXISTS idx_purchase_lines_purchase ON purchase_lines (purchase_id);
CREATE INDEX IF NOT EXISTS idx_notes_company_date ON notes (company_id, date);
CREATE INDEX IF NOT EXISTS idx_notes_invoice ON notes (invoice_id);
CREATE INDEX IF NOT EXISTS idx_notes_purchase ON notes (purchase_id);
CREATE INDEX IF NOT EXISTS idx_note_lines_note ON note_lines (note_id);
CREATE INDEX IF NOT EXISTS idx_payments_company_date ON payments (company_id, date);
CREATE INDEX IF NOT EXISTS idx_payments_invoice ON payments (invoice_id);
CREATE INDEX IF NOT EXISTS idx_payments_purchase ON payments (purchase_id);
CREATE INDEX IF NOT EXISTS idx_journal_entries_company_date ON journal_entries (company_id, date);
CREATE INDEX IF NOT EXISTS idx_journal_lines_entry ON journal_lines (entry_id);
CREATE INDEX IF NOT EXISTS idx_journal_lines_account ON journal_lines (account_id);
CREATE INDEX IF NOT EXISTS idx_journal_lines_party ON journal_lines (party_id);
CREATE INDEX IF NOT EXISTS idx_employees_company ON employees (company_id);
CREATE INDEX IF NOT EXISTS idx_leave_applications_company ON leave_applications (company_id, status);
CREATE INDEX IF NOT EXISTS idx_leave_applications_employee ON leave_applications (employee_id, from_date);
CREATE INDEX IF NOT EXISTS idx_leave_days_application ON leave_application_days (application_id);
CREATE INDEX IF NOT EXISTS idx_leave_adjustments_employee ON leave_adjustments (employee_id);
CREATE INDEX IF NOT EXISTS idx_einvoices_company ON einvoices (company_id, status);
CREATE INDEX IF NOT EXISTS idx_ewaybills_company ON ewaybills (company_id, status);
CREATE INDEX IF NOT EXISTS idx_ewaybills_invoice ON ewaybills (invoice_id);
CREATE INDEX IF NOT EXISTS idx_gst_filing_events_filing ON gst_filing_events (filing_id);
CREATE INDEX IF NOT EXISTS idx_edoc_events_doc ON edoc_events (doc_id);
CREATE INDEX IF NOT EXISTS idx_billing_invoices_company ON billing_invoices (company_id, status);
CREATE INDEX IF NOT EXISTS idx_billing_invoices_paid ON billing_invoices (paid_on);
CREATE INDEX IF NOT EXISTS idx_billing_events_invoice ON billing_events (invoice_id);
CREATE INDEX IF NOT EXISTS idx_tds_deductions_company_date ON tds_deductions (company_id, date);
CREATE INDEX IF NOT EXISTS idx_tds_deductions_party ON tds_deductions (party_id, section);
CREATE INDEX IF NOT EXISTS idx_user_companies_company ON user_companies (company_id);
CREATE INDEX IF NOT EXISTS idx_companies_billing ON companies (billing_company_id);
CREATE INDEX IF NOT EXISTS idx_users_company ON users (company_id);
CREATE INDEX IF NOT EXISTS idx_platform_audit_created ON platform_audit (created_at);
