// More blog articles (same shape as blog.mjs). Evergreen: explain how things work and what to check; limits, rates and dates change, so we point to "confirm the current rule".
export const POSTS2 = [
  {
    slug: 'when-is-an-e-way-bill-needed', label: 'E-way bill basics', date: '2026-10-08', category: 'GST', minutes: 4, service: 'gst',
    title: 'E-Way Bill: When It Is Needed and How to Avoid Problems',
    desc: 'When an e-way bill is required for moving goods, who generates it, what the validity depends on, and the mistakes that lead to detention at the roadside.',
    h1: 'E-way bill: when you need one and how to avoid problems',
    lead: 'An e-way bill is the electronic document that travels with goods in transit. Getting it right keeps trucks moving and avoids penalties.',
    body: [
      { h: 'What it is', p: ['An e-way bill is generated on the GST portal for the movement of goods above a value set by the rules. It records the consignor, the consignee, the goods, the invoice and the vehicle. Officers can check it at any point during the journey.'] },
      { h: 'Who generates it', p: ['Usually the supplier generates it before the goods move. The recipient or the transporter can also generate it in the situations the rules allow. Some movements are exempt, and the value limit and exemptions can change, so confirm the current rule before you dispatch.'] },
      { h: 'What the validity depends on', p: ['Validity is linked to the distance the goods travel. If a delay makes the journey longer than planned, the bill may need to be extended before it expires.'] },
      { h: 'Common mistakes', list: ['Dispatching before generating the bill.', 'Entering a wrong distance, HSN code or vehicle number.', 'Not updating the vehicle number when the goods change vehicles.', 'Letting the bill expire on a delayed journey.', 'Raising an invoice that does not match the bill.'], p: ['Most roadside problems come from mismatched details. A short pre-dispatch checklist prevents nearly all of them.'] },
    ],
    faq: [['Can I cancel an e-way bill?', 'A bill can be cancelled within a short window if the goods were not moved or details were wrong. After that, you generate a fresh one.'], ['Do I need one for local movement?', 'Rules differ by state and by value. We confirm what applies to your route.']],
  },
  {
    slug: 'input-tax-credit-reconciliation-basics', label: 'Input tax credit checks', date: '2026-10-08', category: 'GST', minutes: 5, service: 'gst',
    title: 'Input Tax Credit: Conditions and a Simple Reconciliation',
    desc: 'The conditions for claiming GST input tax credit, why supplier mistakes affect you, and a simple monthly reconciliation routine that avoids reversals.',
    h1: 'Input tax credit: conditions and a simple monthly reconciliation',
    lead: 'Input tax credit lowers the GST you pay, but only when the conditions are met. A short monthly routine protects it.',
    body: [
      { h: 'The basic conditions', p: ['In general you can claim credit when you hold a valid tax invoice or similar document, you have received the goods or services, the supplier has actually filed their return and paid the tax, and you have filed your own return. Some items are blocked from credit by law, so check them before claiming.'] },
      { h: 'Why your supplier’s behaviour matters', p: ['Your credit depends on what your suppliers report. If a supplier does not file or reports a wrong invoice, the credit may not appear in your statement, and claiming it anyway can lead to a notice, interest and reversal.'] },
      { h: 'A simple monthly routine', list: ['Download your auto-generated purchase statement from the GST portal.', 'Match it against your purchase register, invoice by invoice.', 'Claim only what matches and is eligible.', 'Chase the suppliers whose invoices are missing, and keep a note.', 'Reverse credit you must reverse, for example on unpaid or ineligible items.'], p: ['Doing this every month is far easier than doing it once a year.'] },
    ],
    faq: [['What if a supplier never files?', 'The credit for their invoices may be disallowed. Raise it with them early and consider whether to keep buying from them.'], ['Can I claim missed credit later?', 'Only within the time limits in the law. We check the current limit for you.']],
  },
  {
    slug: 'common-tds-mistakes-and-how-to-avoid-them', label: 'TDS mistakes to avoid', date: '2026-10-08', category: 'TDS', minutes: 4, service: 'tds',
    title: 'Common TDS Mistakes and How to Avoid Them',
    desc: 'The TDS errors that lead to interest, late fees and disallowed expenses: wrong section, wrong PAN, late deposit and late return, with simple ways to avoid each.',
    h1: 'Common TDS mistakes and how to avoid them',
    lead: 'TDS is a monthly habit, and most penalties come from small slips repeated every month. Here are the ones to watch.',
    body: [
      { h: 'Deducting under the wrong section', p: ['Each type of payment has its own section, rate and threshold. A wrong section means the wrong amount deducted, which can be treated as a short deduction.'] },
      { h: 'Wrong or missing PAN', p: ['If the deductee’s PAN is wrong or not provided, the rate can be higher and the deductee may not get credit. Verify PANs before the first payment.'] },
      { h: 'Late deposit and late return', p: ['Tax deducted must be deposited by the due date, and the quarterly statement must be filed on time. Delay brings interest and a daily fee. Both are avoidable with a calendar kept by your accountant.'] },
      { h: 'A short checklist', list: ['Keep a list of vendors with PAN and the applicable section.', 'Deduct at the time of credit or payment, whichever is earlier.', 'Deposit the tax before the due date and keep the challan.', 'File the quarterly statement and reconcile it with the tax portal.', 'Issue the certificates to deductees on time.'] },
    ],
    faq: [['What happens if I forget to deduct?', 'You may have to pay the tax yourself with interest, and the expense can be disallowed for your own tax. We help you fix it.'], ['Can I correct a filed TDS return?', 'Yes, through a correction statement. It is better to reconcile before filing.']],
  },
  {
    slug: 'proprietorship-llp-or-private-limited', label: 'Choosing a business entity', date: '2026-10-08', category: 'Company law', minutes: 5, service: 'company-law',
    title: 'Proprietorship, LLP or Private Limited: Which Should You Choose?',
    desc: 'Compare a proprietorship, partnership, LLP, one person company and private limited company on liability, compliance, funding and credibility to pick the right form.',
    h1: 'Proprietorship, LLP or private limited company: which should you choose?',
    lead: 'The structure you start with shapes your liability, your compliance load and your ability to raise money. Here is how the options compare.',
    body: [
      { h: 'Proprietorship', p: ['Simple and cheap to start, with few filings. The owner and the business are the same in law, so the owner is personally liable for the debts. It is hard to bring in investors.'] },
      { h: 'Partnership and LLP', p: ['A partnership is flexible, but partners carry unlimited liability. A limited liability partnership gives partners limited liability with lighter compliance than a company. LLPs are common for professional firms and family businesses.'] },
      { h: 'Private limited company', p: ['A separate legal entity with limited liability, the most familiar structure for investors and for startups that plan to raise funds or issue shares. It has the heaviest compliance, with annual accounts, returns and audit.'] },
      { h: 'How to decide', list: ['Do you plan to raise outside money? A private limited company is usually preferred.', 'How much compliance can you handle? A proprietorship or LLP is lighter.', 'How important is limited liability to you?', 'Who are your customers? Larger buyers often prefer dealing with companies.', 'What are the tax effects for your income level? Confirm with an adviser.'] },
    ],
    faq: [['Can I change the structure later?', 'Yes, a proprietorship or LLP can be converted into a company, though it takes work and some costs. Choosing well at the start saves effort.'], ['What is a one person company?', 'A company with a single owner and limited liability. It suits solo founders who want a company structure.']],
  },
  {
    slug: 'annual-roc-filings-for-companies-and-llps', label: 'Annual ROC filings', date: '2026-10-08', category: 'Company law', minutes: 5, service: 'company-law',
    title: 'Annual ROC Filings for Companies and LLPs: A Checklist',
    desc: 'The yearly Registrar filings for private limited companies and LLPs: financial statements, annual return, director KYC and auditor appointment, in plain words.',
    h1: 'Annual ROC filings for companies and LLPs: a checklist',
    lead: 'Every company and LLP has a yearly rhythm of filings with the Registrar. Missing one costs daily fees, so know what the list is.',
    body: [
      { h: 'For a private limited company', list: ['Financial statements, filed in the annual accounts form after they are approved.', 'Annual return, filed in its own form after the annual general meeting.', 'Director KYC for each director who needs it.', 'Auditor appointment and its related filing.', 'Other event-based filings when directors, capital or the registered office change.'], p: ['The accounts must be approved by the board and the shareholders before they are filed.'] },
      { h: 'For an LLP', p: ['An LLP files a statement of accounts and solvency and an annual return, each in its own form. Designated partners also have their own KYC filing.'] },
      { h: 'What it costs to be late', p: ['Late filings attract a fee that grows each day, and repeated default can lead to penalties on the company and its directors. Long default can lead to the company being struck off. It is far cheaper to file on time.'] },
      { h: 'Making it routine', p: ['Close your books soon after year-end, have the audit done promptly, and calendar the board and shareholder meetings. The filings then follow in sequence.'] },
    ],
    faq: [['Do dormant companies need to file?', 'Yes. Even a company with no business has to file annual accounts and returns unless it takes a formal step to become dormant or closes.'], ['Who signs these filings?', 'Directors or designated partners, with certification by a professional where the form requires it.']],
  },
  {
    slug: 'pf-and-esi-for-new-employers', label: 'PF and ESI for employers', date: '2026-10-08', category: 'Labour', minutes: 4, service: 'pf-esi',
    title: 'PF and ESI for New Employers: Who Must Register',
    desc: 'When a new employer must register for PF and ESI, how contributions are shared between employer and employee, and the monthly steps that keep you compliant.',
    h1: 'PF and ESI for new employers: who must register and what to do monthly',
    lead: 'Hiring your first employees brings new registrations. PF and ESI are the two most common, and each has its own conditions.',
    body: [
      { h: 'Provident fund (PF)', p: ['PF registration depends on the number of employees and on the nature of the establishment. Contributions are made by both employer and employee on the wage covered by the scheme. Employers file a monthly return and pay the contributions through the portal.'] },
      { h: 'Employees’ State Insurance (ESI)', p: ['ESI applies to establishments of a certain size, covering employees whose wages are below the stated limit. Both employer and employee contribute, and the scheme provides medical and related benefits.'] },
      { h: 'The thresholds change', p: ['The number of employees and the wage limits that bring you under each scheme are set by the government and can be revised. We check the current position when you hire.'] },
      { h: 'A monthly routine', list: ['Confirm the month’s attendance and salary.', 'Calculate PF and ESI for each eligible employee.', 'Pay the contributions before the due date.', 'File the monthly returns.', 'Keep the challans and registers for inspection.'] },
    ],
    faq: [['Can an employee opt out of PF?', 'Not in general. There are limited exceptions, and the rules for higher wages differ. We confirm how they apply.'], ['What if I register late?', 'You may owe contributions from the date they became due, with interest. It is better to register as soon as you are covered.']],
  },
  {
    slug: 'payroll-salary-structure-and-payslips', label: 'Salary and payslips', date: '2026-10-08', category: 'Payroll', minutes: 4, service: 'payroll',
    title: 'Payroll Basics: Salary Structure and What a Payslip Should Show',
    desc: 'How a salary structure is built, which statutory deductions apply, and what a clear payslip should show so employees and auditors can follow every figure.',
    h1: 'Payroll basics: salary structure and what a payslip should show',
    lead: 'A clear salary structure and a clear payslip prevent most payroll disputes. Here is how to put them together.',
    body: [
      { h: 'Building the structure', p: ['A salary is usually split into basic pay and allowances, such as house rent allowance and special allowance. The split affects PF, tax and gratuity, so it needs thought, not just a round total.'] },
      { h: 'Statutory deductions', p: ['Depending on the employer and the employee, the deductions can include provident fund, ESI, professional tax and tax deducted at source. Each has its own rules and rates.'] },
      { h: 'What a good payslip shows', list: ['Employee name, code, month and days paid.', 'Each earning component and its amount.', 'Each deduction with a clear label.', 'Net pay and the bank it is paid to.', 'Leave balance, if you track it.'], p: ['A payslip that shows the working lets employees check it themselves.'] },
      { h: 'Year-end', p: ['At the end of the year, employers issue the tax deduction certificate for salary and file the related returns. Keeping monthly records accurate makes this straightforward.'] },
    ],
    faq: [['How often should salaries be paid?', 'Most employers pay monthly. Wage payment rules set timelines, so confirm the one that applies to you.'], ['What is the cost to the company?', 'It is the salary plus the employer’s share of statutory contributions and any benefits, which is why the structure matters.']],
  },
  {
    slug: 'udyam-registration-benefits-and-documents', label: 'Udyam registration guide', date: '2026-10-08', category: 'MSME', minutes: 4, service: 'msme',
    title: 'Udyam Registration: Benefits, Documents and Updates',
    desc: 'What Udyam registration gives a small business, the details you need to register, and how to keep the registration up to date as your business grows.',
    h1: 'Udyam registration: benefits, documents and keeping it current',
    lead: 'Udyam registration is the government’s recognition of micro, small and medium enterprises. It is free to register and opens up several benefits.',
    body: [
      { h: 'What you get', p: ['A registered enterprise can access priority lending, subsidy and support schemes, easier participation in some tenders, and the protection of the rules on timely payment by buyers. The exact benefits depend on the scheme and the state.'] },
      { h: 'What you need', list: ['Aadhaar of the proprietor or authorised signatory.', 'PAN and GST details of the business.', 'Business address and activity details.', 'Bank account details.', 'Investment and turnover figures.'], p: ['The registration is online, and the government charges no fee for it.'] },
      { h: 'Category and updates', p: ['An enterprise is classed as micro, small or medium based on its investment and turnover. As your business grows, the category can change, and the details should be updated. A mismatch with your tax records can cause problems later.'] },
      { h: 'Using the benefits', p: ['Registration alone does not bring money. You still need to apply for the loan or the scheme. We help match your business to schemes that are realistic for you.'] },
    ],
    faq: [['Can I have more than one Udyam registration?', 'One registration per enterprise is allowed, and it can list several activities. Separate enterprises under common ownership are treated together for the limits.'], ['Is a trader eligible?', 'Traders can register, though some scheme benefits are limited. We check each scheme.']],
  },
  {
    slug: 'when-does-a-startup-need-a-valuation', label: 'When you need a valuation', date: '2026-10-08', category: 'Valuation', minutes: 4, service: 'valuation',
    title: 'When Does a Startup Need a Business Valuation?',
    desc: 'The moments a startup needs a valuation: raising money, issuing or transferring shares, granting ESOPs and restructuring, and what a good valuation report contains.',
    h1: 'When does a startup need a business valuation?',
    lead: 'Valuation is not only for fundraising. Several everyday events in a company’s life call for a documented value.',
    body: [
      { h: 'The common triggers', list: ['Raising money from investors, where price per share is agreed.', 'Issuing shares to new shareholders or existing ones.', 'Transferring shares between residents and non-residents.', 'Granting employee stock options and setting their price.', 'Mergers, demergers and group restructuring.'], p: ['For some of these the law requires a valuation by a registered valuer or another qualified professional. We check which applies to your case.'] },
      { h: 'How it is done', p: ['Different methods suit different situations. Early-stage companies are usually valued on expected cash flows or comparable deals, while asset-heavy businesses may rely on net asset values. A good report explains the method and the assumptions.'] },
      { h: 'What a good report contains', list: ['The purpose and the date of the valuation.', 'The business and its financials.', 'The method, with reasons for choosing it.', 'The key assumptions and sensitivity.', 'A clear conclusion.'] },
      { h: 'Plan ahead', p: ['Asking for a valuation at the last minute leaves little time to fix gaps in the numbers. Keep clean accounts and a current cap table, and the exercise is much quicker.'] },
    ],
    faq: [['Is valuation the same as the price investors pay?', 'No. Investors negotiate their own price. A valuation gives a reasoned starting point and supports your filings.'], ['How long is a valuation valid?', 'Reports are tied to a date and to the purpose. Rules for how long they can be relied on vary, so we confirm for your case.']],
  },
  {
    slug: 'import-export-code-iec-explained', label: 'Import-Export Code (IEC)', date: '2026-10-08', category: 'Registrations', minutes: 4, service: 'registrations',
    title: 'Import-Export Code (IEC): Who Needs It and How to Get It',
    desc: 'What an Import-Export Code is, who needs one, what it takes to apply, and how to keep it valid, with notes for sellers who export goods or services.',
    h1: 'Import-Export Code (IEC): who needs it and how to get it',
    lead: 'If you ship goods across the border, an Import-Export Code is the first registration to sort out.',
    body: [
      { h: 'What it is', p: ['The IEC is a registration issued by the foreign trade authority. It is linked to the PAN of the business and is needed for customs clearance and for many export-related banking and incentive processes.'] },
      { h: 'Who needs it', p: ['Anyone importing or exporting goods needs one. Service exporters have lighter rules, but banks and some incentive schemes may still ask for it. We confirm the position for your business before you apply.'] },
      { h: 'What you need to apply', list: ['PAN of the business or proprietor.', 'Bank account details, with a cancelled cheque or statement.', 'Address proof of the business premises.', 'Digital signature or Aadhaar verification, as the process requires.', 'Details of the activity and the authorised person.'] },
      { h: 'Keeping it valid', p: ['The code needs to be kept up to date. Details should be updated when your address, bank account or constitution change, and the registration may need a periodic confirmation. Missed updates can block your shipments.'] },
    ],
    faq: [['Does the IEC expire?', 'Once issued it generally stays valid, but you must update it as the rules require. We track that for you.'], ['Do I need GST registration too?', 'Exporters usually need GST registration to export under the usual routes and claim refunds. We help with both.']],
  },
];
