// All the words on the Apbiz website live here. build.mjs turns them into pages. Edit text here, then run: node sites/apbiz/build.mjs
// Rules followed: no invented clients, numbers, awards or credentials; no section numbers or money thresholds that the new Income-tax Act
// (in force from April 2026) or GST notifications may change; every page says to confirm current rules.

export const SITE = {
  name: 'Apbiz',
  legal: 'Apbiz Consulting India LLP',
  url: 'https://apbiz.in',
  phone: '+91 78939 13456',
  phoneDigits: '917893913456',
  email: 'sivaravella@o2labs.com',
  updated: '2026-10-08',
  software: 'https://ibmp.apbiz.in',
};

export const SERVICES = [
  {
    slug: 'gst', icon: 'receipt', name: 'GST',
    short: 'Registration, monthly and annual returns, e-invoicing, e-way bills, refunds and notices.',
    title: 'GST Registration, Returns and Notices in India | Apbiz',
    desc: 'GST registration, GSTR-1 and GSTR-3B filing, annual return, e-invoicing, e-way bills, refunds and replies to GST notices for Indian businesses.',
    h1: 'GST registration, returns and notices, handled.',
    lead: 'From getting your GSTIN to filing every return and answering the department, we keep your GST in order so that tax is never the reason a deal, a loan or a refund gets stuck.',
    intro: [
      'Goods and Services Tax touches every invoice you raise and every bill you pay. A small mistake, such as the wrong rate, a missed input credit or a return filed late, quietly turns into interest, a blocked e-way bill or a notice months later.',
      'Apbiz sets up your GST correctly the first time and then runs it month after month: reconciling your purchases with what suppliers have actually reported, preparing returns for your approval, and filing them before the due date.',
    ],
    includes: [
      ['GST registration and amendments', 'New registration, changes of address, partners or business activity, and cancellation when a business closes.'],
      ['Monthly and quarterly returns', 'GSTR-1 for sales and GSTR-3B for the tax payment, under the monthly or the quarterly (QRMP) scheme, or the composition scheme if you qualify.'],
      ['Input tax credit reconciliation', 'Purchases matched against your GSTR-2B so you claim the credit you are entitled to, and chase suppliers for the rest.'],
      ['E-invoicing and e-way bills', 'Set-up and day-to-day support for businesses that must issue e-invoices or move goods that need an e-way bill.'],
      ['Annual return and reconciliation', 'The annual GST return and the books-to-returns reconciliation, with differences explained before the department asks.'],
      ['Refunds, LUT and exports', 'Letter of Undertaking for exporters, refund claims for exports or inverted duty, and follow-up until the money arrives.'],
      ['Notices, scrutiny and appeals', 'Reading the notice, collecting the documents, drafting the reply and, where needed, preparing an appeal.'],
    ],
    who: ['Traders, manufacturers and service providers above the registration limit, and those who register voluntarily', 'E-commerce sellers and exporters', 'Businesses that received a GST notice or a mismatch communication', 'Companies preparing for an audit, loan or investment'],
    steps: [
      ['Review', 'We look at your registration, sales and purchase pattern and tell you which GST scheme and return frequency suit you.'],
      ['Run', 'You send invoices and bank data. We reconcile, prepare the returns and share the tax payable for your approval.'],
      ['File and confirm', 'We file before the due date, send you the acknowledgement and keep a clean record for audits and notices.'],
    ],
    docs: ['PAN of the business or proprietor', 'Proof of address of the place of business', 'Bank account details', 'Sales and purchase invoices for the period', 'Login details or a delegated access for the GST portal'],
    faq: [
      ['Who has to register for GST?', 'Registration depends on your annual turnover and the kind of business. The limits differ for goods and services and for some states, and some businesses must register regardless of turnover, such as many e-commerce sellers. Send us your details and we will tell you where you stand.'],
      ['How often do I file GST returns?', 'Most regular businesses file GSTR-1 and GSTR-3B every month. Smaller businesses can choose the quarterly scheme, and composition taxpayers follow a different, simpler pattern. We choose the right option for you and keep track of every date for you.'],
      ['What happens if I file late?', 'Late fees and interest apply for each day or month of delay, and a series of missed returns can lead to suspension of registration and a blocked e-way bill. It is far cheaper to file on time, and we help you catch up if you are behind.'],
      ['Can you help if I have already received a GST notice?', 'Yes. Do not ignore it, because the reply period is short. Send us the notice and we will explain what it means, what is being asked and how to respond.'],
      ['Do I need e-invoicing?', 'E-invoicing applies to businesses above a prescribed turnover. The limit has been reduced over time, so we check the current rule against your turnover.'],
    ],
    related: ['income-tax', 'accounting', 'registrations'],
    wa: 'GST',
  },
  {
    slug: 'income-tax', icon: 'percent', name: 'Income tax',
    short: 'Returns for individuals, firms, LLPs and companies, advance tax, tax planning and notices.',
    title: 'Income Tax Return Filing and Tax Planning for Businesses | Apbiz',
    desc: 'Income tax return filing for individuals, proprietors, firms, LLPs and companies, advance tax, tax audit support, tax planning and replies to income tax notices.',
    h1: 'Income tax returns and planning, without the last-minute rush.',
    lead: 'We prepare and file your returns accurately, plan advance tax so there are no surprises, and deal with the department when a notice arrives.',
    intro: [
      'Income tax is where small business owners most often feel exposed: the choice between tax regimes, advance tax instalments, presumptive taxation, audit requirements and the long list of documents that have to agree with each other.',
      'Our work is to make those decisions early, with your numbers in front of us, so the return you file is the one you meant to file and the tax you pay is no more than the law requires.',
    ],
    includes: [
      ['Returns for every kind of taxpayer', 'Salaried individuals with business or capital gains income, proprietors, professionals, partnership firms, LLPs and companies.'],
      ['Regime and structure advice', 'A comparison of the available tax regimes and presumptive options for your case, before the year ends, not after.'],
      ['Advance tax planning', 'Estimates of liability and reminders for each instalment, so interest for short payment is avoided.'],
      ['Tax audit support', 'Preparation of the data and schedules for businesses and professionals who need a tax audit, and coordination with the auditor.'],
      ['Capital gains and investments', 'Gains on shares, mutual funds, property and other assets, with the working you need to defend the figures.'],
      ['Notices and rectification', 'Intimations, defective-return notices, mismatches with Form 26AS or the annual information statement, and rectification requests.'],
      ['Tax computation for lenders and visas', 'Computations and acknowledgements in the format banks and consulates ask for.'],
    ],
    who: ['Business owners and professionals who want a second pair of eyes before they file', 'Directors and partners with several sources of income', 'Companies and LLPs that must file every year, even with no activity', 'Anyone who has received an income tax notice'],
    steps: [
      ['Collect', 'You share your documents or give us access to your books. We list anything missing.'],
      ['Compute and advise', 'We prepare the computation, show the tax under the options open to you and recommend one.'],
      ['File and follow up', 'You approve, we file and e-verify with you, and we track processing and any refund.'],
    ],
    docs: ['PAN and Aadhaar', 'Bank statements and interest certificates', 'Form 16 or salary statements', 'Profit and loss account and balance sheet for business income', 'Capital gains statements and investment proofs', 'Form 26AS and the annual information statement'],
    faq: [
      ['What is the due date for filing an income tax return?', 'It depends on who you are. Many individuals who need no audit file by 31 July, while taxpayers whose accounts must be audited have a later date, and companies and LLPs have their own. Dates are sometimes extended, so we confirm the current one for you.'],
      ['Do I need to pay advance tax?', 'If your estimated tax for the year is above a small limit after TDS, advance tax is payable in instalments through the year. Late or short payment attracts interest. We estimate your liability and remind you of each date.'],
      ['Which tax regime is better for me?', 'There is no single answer. It depends on your income, deductions and whether you have business income. We compute both for your numbers and explain the difference in plain terms.'],
      ['I got a notice from the income tax department. What now?', 'Read it carefully and note the response date. Many notices are routine mismatches that can be cleared with a document or a rectification. Send it to us and we will tell you what it means and what to do.'],
      ['Is a return required if my company had no business?', 'Yes. Companies and LLPs must file returns every year even when there is no income, and missing them leads to penalties and difficulties later.'],
    ],
    related: ['tds', 'accounting', 'gst'],
    wa: 'income tax',
  },
  {
    slug: 'tds', icon: 'download', name: 'TDS and TCS',
    short: 'TAN, deduction and deposit, quarterly returns, Form 16 and 16A, and TRACES notices.',
    title: 'TDS and TCS Compliance: Returns, Form 16 and Notices | Apbiz',
    desc: 'TDS and TCS compliance in India: TAN registration, correct deduction and deposit, quarterly returns (24Q, 26Q, 27Q), Form 16 and 16A, corrections and TRACES notices.',
    h1: 'TDS and TCS compliance, deducted, deposited and filed right.',
    lead: 'If you pay salaries, rent, professionals or contractors, you are collecting tax for the government. We make sure it is deducted at the right rate, deposited on time and reported correctly.',
    intro: [
      'TDS looks simple until you meet the rates, the thresholds, the different return forms and the TRACES portal. Mistakes are expensive, because the department charges interest on late deduction and late deposit, and a fee for every day a return is delayed. The deductee also loses credit if you report their PAN wrongly.',
      'Apbiz takes over the whole cycle: working out what to deduct, paying it, filing the quarterly statements and issuing certificates, so your vendors and employees get their credit and you stay clear of defaults.',
    ],
    includes: [
      ['TAN registration and updates', 'New TAN applications and corrections to your TAN details.'],
      ['Rate and threshold checks', 'Which payments attract TDS, at what rate and above what limit, including the lower or nil rate where a certificate is available.'],
      ['Monthly challan and deposit', 'Calculation of the amount payable by the 7th of each month and preparation of the challan.'],
      ['Quarterly TDS returns', 'Returns for salary (24Q), resident payments (26Q), payments to non-residents (27Q) and TCS (27EQ), filed with the right deductee details.'],
      ['Form 16 and Form 16A', 'Certificates for employees and for vendors, issued on time so that they can claim credit.'],
      ['Corrections and TRACES notices', 'Correction statements, default notices, justification reports and short-deduction demands.'],
      ['Lower deduction certificates', 'Applications for a lower or nil rate where your income justifies it.'],
    ],
    who: ['Employers who run payroll', 'Companies, firms and professionals who pay rent, professional fees, commission or contractors', 'Businesses that sell goods covered by tax collected at source', 'Anyone who has received a TDS default notice'],
    steps: [
      ['Map', 'We list your payments and mark which ones carry TDS or TCS and at what rate.'],
      ['Deduct and deposit', 'Each month we compute the amount, you approve it, and we prepare the challan before the 7th.'],
      ['Return and certify', 'Each quarter we file the return, then issue certificates, and fix any correction that comes up.'],
    ],
    docs: ['TAN and PAN', 'Salary register or payment ledger', 'Vendor and employee PANs', 'Challan details of deposits made', 'Previous returns, if any'],
    faq: [
      ['When must TDS be deposited?', 'Generally by the 7th of the month following the month of deduction, with a different date for March. Late deposit attracts interest, so we track the date for you every month.'],
      ['What are the due dates for TDS returns?', 'Quarterly: 31 July, 31 October, 31 January and 31 May for the four quarters of the year. Form 16 for salaries follows after the year-end return.'],
      ['What happens if I deduct TDS but pay it late?', 'Interest is charged for every month or part of a month of delay at a higher rate than for late deduction, and late filing of the return also carries a daily fee. It is better to pay late than never, but better still to pay on time.'],
      ['Why does my vendor say their TDS credit is missing?', 'Usually a wrong PAN, a return not filed, or a challan not matched to the statement. We trace it and file a correction.'],
      ['Do I need a TAN?', 'Yes. Any person who deducts or collects tax must obtain a TAN and quote it in challans, returns and certificates.'],
    ],
    related: ['payroll', 'income-tax', 'gst'],
    wa: 'TDS',
  },
  {
    slug: 'company-law', icon: 'building', name: 'Company law (ROC / MCA)',
    short: 'Incorporation, annual filings, director KYC and secretarial compliance for companies and LLPs.',
    title: 'Company and LLP Registration and Annual ROC Compliance | Apbiz',
    desc: 'Private limited company, LLP and OPC registration, annual ROC filings (AOC-4, MGT-7, LLP Form 11 and 8), director KYC and secretarial compliance in India.',
    h1: 'Company and LLP registration and annual ROC compliance.',
    lead: 'Start the right entity the right way, and keep it in good standing every year, with every Registrar of Companies filing done on time.',
    intro: [
      'A company or LLP is a separate legal person, and the law expects it to behave like one: board meetings, books, annual accounts and a steady rhythm of filings with the Ministry of Corporate Affairs. Missing them does not make the company disappear. It makes the penalties, and the directors’ difficulties, add up quietly.',
      'We help you pick the right structure, incorporate it with clean documents, and then keep up the yearly cycle so that you can raise money, open accounts and sell the business without a clean-up exercise first.',
    ],
    includes: [
      ['Choosing the structure', 'Private limited company, LLP, one person company or partnership: the trade-offs in tax, liability, funding and compliance cost.'],
      ['Incorporation', 'Name approval, director identification numbers, the incorporation form, the constitutional documents and the first set of PAN, TAN and bank formalities.'],
      ['Annual filings for companies', 'Financial statements (AOC-4), the annual return (MGT-7), the auditor appointment and the director KYC.'],
      ['Annual filings for LLPs', 'The statement of accounts and solvency (Form 8) and the annual return (Form 11).'],
      ['Changes to the company', 'Adding or removing directors and partners, changing the registered office, name, objects or share capital.'],
      ['Board and shareholder paperwork', 'Notices, agendas, minutes and resolutions for board and general meetings, and statutory registers.'],
      ['Closing down a company', 'Striking off a dormant company or closing an LLP properly.'],
    ],
    who: ['Founders starting a business', 'Existing proprietors and partnerships moving into a company or LLP', 'Companies behind on their yearly filings', 'Startups preparing for investment or due diligence'],
    steps: [
      ['Plan', 'We learn who the founders are, what the business does and how it will be funded, and recommend a structure.'],
      ['Incorporate or catch up', 'We prepare documents, file with the registrar and, for existing entities, list every missed form and its cost.'],
      ['Stay current', 'We track each annual and event-based filing and complete it for your approval and signature.'],
    ],
    docs: ['PAN and Aadhaar of directors or partners', 'Passport-size photographs and address proofs', 'Proof of the registered office with a no-objection letter from the owner', 'Proposed company names', 'Financial statements and the auditor’s report for annual filings'],
    faq: [
      ['What do I need to start a private limited company?', 'At least two directors, one of whom must be a resident in India, at least two shareholders, a registered office in India and a unique name. We take care of the filings and documents.'],
      ['What are the yearly ROC filings for a company?', 'The annual general meeting within six months of the financial year-end, then the financial statements and the annual return within the prescribed number of days of the meeting, plus director KYC and auditor-related forms. We give you the exact dates for your company.'],
      ['What happens if I miss an ROC filing?', 'An additional fee is charged for each day of delay, and prolonged default can lead to disqualification of directors and strike-off of the company. It is usually much cheaper to catch up early.'],
      ['Should I choose an LLP or a private limited company?', 'It depends on whether you expect outside investment, how you want to share profits, and how much compliance you are ready for. We compare them for your situation.'],
      ['Do I have to file returns if the company is not operating?', 'Yes. Even a dormant company must file annual accounts and returns unless it is formally struck off or has taken the dormant status.'],
    ],
    related: ['income-tax', 'registrations', 'accounting'],
    wa: 'company or LLP compliance',
  },
  {
    slug: 'pf-esi', icon: 'shield', name: 'PF, ESI and professional tax',
    short: 'Registrations, monthly contributions and returns for provident fund, ESI and professional tax.',
    title: 'PF, ESI and Professional Tax Registration and Returns | Apbiz',
    desc: 'Provident fund (EPF), ESI and professional tax registration, monthly contribution and return filing for employers in India, with reminders before each due date.',
    h1: 'PF, ESI and professional tax, registered and filed every month.',
    lead: 'The rules for employees’ benefits are strict about dates. We register your establishment, calculate every contribution and file on time, so your team’s benefits and your compliance stay intact.',
    intro: [
      'Once you have employees, you have obligations to them and to the authorities: provident fund, state insurance, professional tax in many states, and the registers that go with them. The contributions are due every month, usually by the 15th, and the penalties for delay are charged as interest and damages.',
      'Apbiz handles registration and the monthly cycle, and keeps the records in a form an inspector would accept.',
    ],
    includes: [
      ['EPF registration and employer codes', 'Establishment registration, employer and employee portal access and the UAN for each employee.'],
      ['Monthly EPF contribution and ECR', 'Calculation, payment and electronic return filing by the due date.'],
      ['ESI registration and contributions', 'Employer registration, insurance numbers for employees and monthly contribution payment.'],
      ['Professional tax', 'Enrolment and registration and periodic returns in the states that levy it, matched to each state’s rates and dates.'],
      ['Employee changes', 'Joining and exit entries, transfers of accounts and corrections to names, dates and wages.'],
      ['Claims and inspections', 'Help with claims and responses to notices or inspections.'],
    ],
    who: ['Employers who have reached the headcount where registration is required', 'Businesses that hire their first employees', 'Companies that operate in several states', 'Employers who received an inspection or damages notice'],
    steps: [
      ['Assess', 'We check headcount, wages and states, and tell you which registrations apply and from when.'],
      ['Register', 'We apply, activate your portal logins and set up your employees.'],
      ['Run monthly', 'Each month we compute, you approve, we pay and file, and send the receipts.'],
    ],
    docs: ['PAN, incorporation or partnership papers', 'Address proof and bank details', 'Employee list with Aadhaar, PAN, wages and date of joining', 'Digital signature of the authorised person'],
    faq: [
      ['When does PF registration become mandatory?', 'Generally when an establishment reaches the prescribed number of employees. Smaller employers can register voluntarily, and many do because it helps with hiring.'],
      ['When are PF and ESI contributions due?', 'Typically by the 15th of the following month. We track the date and prepare the challan before it.'],
      ['Does every state levy professional tax?', 'No. It is a state tax, so whether it applies and at what rate depends on where your employees work. We check the states you operate in.'],
      ['What if I paid late?', 'Interest and damages are levied for the period of delay. Pay as early as possible and tell us, and we will compute what is due and help with any notice.'],
      ['Will you also run my payroll?', 'Yes. Payroll and these statutory payments belong together, and we offer them as a single service.'],
    ],
    related: ['payroll', 'tds', 'registrations'],
    wa: 'PF and ESI',
  },
  {
    slug: 'payroll', icon: 'wallet', name: 'Payroll',
    short: 'Salary processing, payslips, statutory deductions, Form 16 and full-and-final settlement.',
    title: 'Payroll Processing, Payslips and Statutory Deductions | Apbiz',
    desc: 'Payroll processing for Indian businesses: salary calculation, payslips, PF, ESI, professional tax and TDS on salary, Form 16 and full-and-final settlement.',
    h1: 'Payroll that is correct every month.',
    lead: 'Salaries are the one payment your team notices immediately. We calculate them accurately, pay the statutory dues on time and give each employee a clear payslip.',
    intro: [
      'Payroll sits where accounting, tax and labour law meet. A salary structure affects how much tax an employee pays, how much you contribute, and what a settlement looks like when someone leaves. Getting it wrong shows up first as unhappy employees and later as notices.',
      'Apbiz designs the salary structure, runs payroll each month and takes care of every deduction and payment that follows from it.',
    ],
    includes: [
      ['Salary structure design', 'Basic, allowances and reimbursements arranged so they are compliant and tax-efficient for the employee.'],
      ['Monthly payroll processing', 'Attendance and leave, earnings, deductions, arrears and the net pay for each person.'],
      ['Payslips and registers', 'Clear payslips for every employee and the payroll registers you need to keep.'],
      ['Statutory deductions and payments', 'PF, ESI, professional tax and tax deducted from salary, calculated and paid on time.'],
      ['Form 16 and the annual cycle', 'Year-end tax computation for each employee and Form 16 for the whole team.'],
      ['Bonus, gratuity and leave encashment', 'Calculations as and when they fall due.'],
      ['Joining and exit', 'Offer-letter checks, onboarding entries and full-and-final settlements.'],
    ],
    who: ['Growing teams that outgrew spreadsheets', 'Startups that need payroll without a full-time HR person', 'Companies in several states with different rules', 'Businesses that want a clean audit trail for salaries'],
    steps: [
      ['Set up', 'We take your employee list and structures and set up the payroll rules.'],
      ['Process', 'Each month you send attendance and changes. We process and share the summary for approval.'],
      ['Pay and report', 'We prepare the bank file and statutory payments, deliver payslips and update the books.'],
    ],
    docs: ['Employee master data and bank accounts', 'Offer letters or salary structures', 'Monthly attendance and leave', 'Previous payroll records and tax declarations'],
    faq: [
      ['What do you need from me each month?', 'The changes: joiners, leavers, attendance or leave and any one-time payments. We take it from there.'],
      ['Do you also pay the statutory dues?', 'We calculate and prepare them, and file the related returns. The payment itself is made from your account on your approval, unless you ask us to arrange it differently.'],
      ['Can you handle employees in different states?', 'Yes. State rules for professional tax and for registration differ, and we apply the right ones to each location.'],
      ['How do employees declare their investments for tax?', 'We collect declarations at the start of the year, adjust the deduction through the months and issue Form 16 after the year-end.'],
      ['What happens when someone resigns?', 'We calculate the final settlement: salary, leave encashment, bonus or gratuity if due, and recoveries, and update every statutory record.'],
    ],
    related: ['pf-esi', 'tds', 'accounting'],
    wa: 'payroll',
  },
  {
    slug: 'registrations', icon: 'filecheck', name: 'Registrations and licences',
    short: 'Udyam, Shops and Establishment, FSSAI, Import-Export Code, PAN, TAN and trade licences.',
    title: 'Udyam, Shops and Establishment, FSSAI and IEC Registration | Apbiz',
    desc: 'Business registrations and licences in India: Udyam (MSME), Shops and Establishment, FSSAI food licence, Import-Export Code, PAN, TAN and local trade licences.',
    h1: 'Business registrations and licences, sorted.',
    lead: 'The right registrations open doors: bank loans, government schemes, imports and exports, and the trust of larger customers. We find which ones you need and get them done.',
    intro: [
      'Running a business in India often needs more than one registration, and the list depends on what you do, where you do it and how big you are. Some are free and quick, some depend on your state or city, and some must be renewed.',
      'We tell you what applies to you, prepare the applications and keep track of the renewals.',
    ],
    includes: [
      ['Udyam registration (MSME)', 'The online registration that unlocks priority-sector lending and a range of government benefits for micro, small and medium enterprises.'],
      ['Shops and Establishment', 'The state registration for shops, offices and commercial establishments, with renewals and amendments.'],
      ['FSSAI food licence', 'Registration or licence for food businesses, matched to your size and activities, with renewals.'],
      ['Import-Export Code (IEC)', 'The code needed to import or export goods, with updates when details change.'],
      ['PAN and TAN', 'New applications and corrections.'],
      ['Trade licences and local permissions', 'Municipal and other local approvals that apply to your premises and activity.'],
      ['GST and professional tax enrolments', 'Registered for you as part of the same set-up, so everything is aligned from the start.'],
    ],
    who: ['New businesses setting up their first office or shop', 'Food businesses, restaurants and caterers', 'Importers, exporters and e-commerce sellers', 'MSMEs that want credit or scheme benefits'],
    steps: [
      ['Identify', 'We ask about your activity, premises and size and list the registrations that apply.'],
      ['Apply', 'We collect documents, prepare and submit the applications and respond to queries.'],
      ['Renew', 'We track each renewal and amendment so nothing lapses.'],
    ],
    docs: ['PAN and Aadhaar of the owner or authorised person', 'Address proof of the premises, with rent or ownership papers', 'Bank account details', 'Photographs and activity details', 'Incorporation or partnership documents'],
    faq: [
      ['Is Udyam registration compulsory?', 'It is not compulsory for running a business, but it is needed for many benefits for small enterprises, so most eligible businesses register.'],
      ['Which FSSAI licence do I need?', 'It depends on the type of food business and its turnover or capacity. We check which category applies and apply for it.'],
      ['Do I need an IEC to export services?', 'An Import-Export Code is needed to import or export goods. For services the rules are lighter, but some incentives and banking transactions still ask for it. We confirm for your case.'],
      ['Are registrations done by the state or the centre?', 'Both. Udyam and IEC are central, while Shops and Establishment, trade licences and professional tax are state or local. We handle each at its own office or portal.'],
      ['How long does registration take?', 'It varies by registration and by state and by how quickly documents are in order. We tell you what to expect before we start.'],
    ],
    related: ['gst', 'company-law', 'pf-esi'],
    wa: 'registrations and licences',
  },
  {
    slug: 'accounting', icon: 'book', name: 'Accounting and bookkeeping',
    short: 'Monthly bookkeeping, reconciliations, financial statements and MIS that your tax filings can rely on.',
    title: 'Accounting, Bookkeeping and Financial Statements | Apbiz',
    desc: 'Monthly accounting and bookkeeping for Indian businesses: bank reconciliation, GST-ready books, financial statements, MIS reports and audit support.',
    h1: 'Books you can trust, ready for every filing.',
    lead: 'Every return starts with the books. We keep them accurate and current, so GST, income tax, TDS and audits all pull from one reliable record.',
    intro: [
      'Good compliance is a by-product of good books. When sales, purchases and bank entries are recorded correctly and promptly, returns practically prepare themselves, and a notice becomes a request for documents instead of a crisis.',
      'Apbiz keeps your accounts month by month, reconciles them with the bank and the tax portals, and gives you reports that are simple enough to use.',
    ],
    includes: [
      ['Monthly bookkeeping', 'Sales, purchases, expenses and bank entries recorded and classified correctly.'],
      ['Bank and ledger reconciliation', 'Bank statements, customers and suppliers matched, with differences explained.'],
      ['GST and TDS-ready books', 'Entries structured so returns and certificates can be prepared directly from them.'],
      ['Financial statements', 'Profit and loss account, balance sheet and notes at year-end, prepared for your auditor and the filings.'],
      ['MIS reports', 'A short monthly summary of sales, costs, receivables, payables and cash.'],
      ['Audit and due-diligence support', 'Schedules and documents for statutory auditors, lenders and investors.'],
      ['Clean-up of old books', 'Reconstruction of past years where records are incomplete.'],
    ],
    who: ['Owner-managed businesses without a finance team', 'Startups getting ready for funding', 'Businesses that fell behind on their books', 'Companies that want one view of cash, tax and compliance'],
    steps: [
      ['Set up', 'We agree the chart of accounts and how you will share documents and bank data.'],
      ['Record monthly', 'We post, reconcile and close each month and send a short summary.'],
      ['Close the year', 'We prepare the financial statements and hand over everything your auditor and filings need.'],
    ],
    docs: ['Sales and purchase invoices', 'Bank and card statements', 'Expense bills and payroll registers', 'Loan and asset details', 'Opening balances from the previous year'],
    faq: [
      ['Which accounting software do you use?', 'We can work in the software you already use, or on IBMP, our own platform for Indian businesses, which keeps GST, payroll and TDS together with the books.'],
      ['How often will I see my numbers?', 'Every month, in a short report. You can ask for a quick view any time in between.'],
      ['Can you fix books that are months behind?', 'Yes. We start with the oldest unreconciled period, rebuild forward and tell you what each step costs in time before we begin.'],
      ['Do you also do audits?', 'We prepare for audits and coordinate with the auditor. A statutory audit itself must be done by a qualified independent auditor, and we can work with yours.'],
      ['Is my financial data safe?', 'We use your documents only for the work you ask for, and we limit who can see them. Tell us if you need specific confidentiality terms.'],
    ],
    related: ['gst', 'income-tax', 'payroll'],
    wa: 'accounting and bookkeeping',
  },
  {
    slug: 'startup-india', icon: 'rocket', name: 'DPIIT and Startup India',
    short: 'DPIIT recognition, Startup India benefits, tax exemption applications and investor-ready compliance for startups.',
    title: 'DPIIT Recognition and Startup India Registration | Apbiz',
    desc: 'DPIIT startup recognition, Startup India benefits, Section 80-IAC and angel tax queries, and investor-ready compliance for Indian startups, handled end to end.',
    h1: 'DPIIT recognition and Startup India, handled for you.',
    lead: 'Recognition by DPIIT opens up the Startup India benefits. We check that you qualify, prepare the application and keep your startup compliant as it grows.',
    intro: [
      'Startup India is the central government programme for new businesses. A company or LLP recognised by the Department for Promotion of Industry and Internal Trade (DPIIT) can apply for benefits such as tax exemptions, easier compliance and support in public procurement.',
      'The recognition has conditions on age, turnover and the nature of the business. Apbiz checks them first, prepares the application and describes your innovation clearly, then helps you use the benefits you are entitled to.',
    ],
    includes: [
      ['Eligibility check', 'Entity type, age, turnover and the innovation or scalability angle reviewed before you apply.'],
      ['DPIIT recognition', 'Application prepared and filed on the Startup India portal, with replies to any queries.'],
      ['Tax exemption applications', 'Support with the income tax exemption for eligible startups and the related approvals.'],
      ['Angel tax and investor queries', 'Valuation and documentation support when you raise money from investors.'],
      ['Incorporation first, if needed', 'Private limited company or LLP formation so you have an eligible entity.'],
      ['Self-certification support', 'Guidance on the labour and environment law compliances that startups can self-certify.'],
      ['Investor-ready compliance', 'Statutory books, filings and share records organised for due diligence.'],
    ],
    who: ['Founders registering their first company or LLP', 'Early-stage startups planning to raise funds', 'Product and technology businesses with an innovative model', 'Startups that want to use government schemes and tenders'],
    steps: [
      ['Check', 'We confirm that your entity and idea meet the recognition conditions.'],
      ['Apply', 'We prepare the documents and the description of your innovation and submit on the portal.'],
      ['Use the benefits', 'We apply for the exemptions and schemes that suit you and keep your filings current.'],
    ],
    docs: ['Certificate of incorporation or LLP registration', 'PAN of the entity and the founders', 'A short description of the product and what is new about it', 'Website or pitch material, if available', 'Authorisation letter for the person applying'],
    faq: [
      ['Who can get DPIIT recognition?', 'A private limited company, an LLP or a registered partnership firm within the age and turnover limits, working on an innovative product, process or service or on a scalable model. We check the current conditions for you.'],
      ['Is recognition the same as the tax exemption?', 'No. Recognition comes first. The income tax exemption is a separate application with its own conditions, and we help with both.'],
      ['Does it cost anything to get recognised?', 'The Startup India recognition itself has no government fee. Our fee covers preparing and following up the application. We tell you the amount before we begin.'],
      ['Can I apply before incorporating?', 'No, recognition is given to a registered entity. We can incorporate it for you first.'],
      ['How long does it take?', 'It depends on how complete the application is and how quickly the department responds. We share realistic timing once we have seen your documents.'],
    ],
    related: ['company-law', 'valuation', 'msme'],
    wa: 'DPIIT and Startup India',
  },
  {
    slug: 'msme', icon: 'briefcase', name: 'MSME and Udyam benefits',
    short: 'Udyam registration, MSME schemes, subsidies, collateral-free loan support and delayed-payment remedies.',
    title: 'Udyam (MSME) Registration, Schemes and Subsidies | Apbiz',
    desc: 'Udyam registration, updates and MSME scheme support for Indian small businesses: priority lending, subsidies, tender benefits and delayed-payment remedies.',
    h1: 'Make your MSME status work for you.',
    lead: 'Udyam registration is only the start. We register you, keep the details current and help you claim the schemes, loans and protections meant for small businesses.',
    intro: [
      'Micro, small and medium enterprises have access to schemes that larger firms do not, from priority-sector lending to payment protection against late-paying buyers. Many owners register and then never use the benefits.',
      'Apbiz handles the Udyam registration, corrects and updates it when your turnover or activity changes, and walks you through the schemes that suit your business.',
    ],
    includes: [
      ['Udyam registration', 'New registration and the certificate, with the right activity codes for your business.'],
      ['Updates and corrections', 'Changes to turnover, investment, address, activity and ownership details.'],
      ['Scheme matching', 'A short list of central and state schemes and subsidies you can realistically apply for.'],
      ['Loan and credit support', 'Documents and presentation for bank loans, including guarantee-backed lending for small businesses.'],
      ['Delayed-payment remedies', 'Help in using the MSME rules on timely payment when a buyer does not pay on time.'],
      ['Tender and procurement registrations', 'Support for enlisting on government procurement platforms.'],
      ['Annual hygiene', 'A yearly check that your registration and related records are up to date.'],
    ],
    who: ['Manufacturers, traders and service providers', 'Small businesses planning to take a bank loan', 'Suppliers waiting on late payments from large buyers', 'Businesses that want to bid for government tenders'],
    steps: [
      ['Register or update', 'We prepare your Udyam details from your PAN, GST and business information.'],
      ['Match', 'We list the schemes and benefits that fit your size, activity and state.'],
      ['Apply and follow up', 'We prepare the applications and track them until they are decided.'],
    ],
    docs: ['Aadhaar of the proprietor or authorised signatory', 'PAN and GSTIN of the business', 'Bank account details', 'Turnover and investment figures', 'Activity and address details'],
    faq: [
      ['Is there a fee for Udyam registration?', 'The government registration itself is free. Our fee, if you use us, covers preparing the details correctly and supporting you afterwards.'],
      ['Does my category change as my business grows?', 'Yes. The category depends on investment and turnover, and the details linked to your PAN and GST are used to update it. We help you review it each year.'],
      ['What is the benefit of registering?', 'Registered businesses can access priority lending, many scheme subsidies, and the rules on timely payment by buyers. The benefits depend on the scheme and the state.'],
      ['Can a trader or service provider register?', 'Yes. Both manufacturing and service enterprises can register, and traders can register too, though some schemes are not open to them. We check each scheme for you.'],
      ['Will you guarantee a subsidy or a loan?', 'No. Approvals are decided by the authority or the bank. We make sure your application is complete and well presented.'],
    ],
    related: ['startup-india', 'registrations', 'fssai-licences'],
    wa: 'MSME and Udyam',
  },
  {
    slug: 'fssai-licences', icon: 'store', name: 'FSSAI and business licences',
    short: 'FSSAI registration and licence, renewals and returns, plus trade, drug, fire and other licences.',
    title: 'FSSAI Licence, Trade and Other Business Licences | Apbiz',
    desc: 'FSSAI registration, licence, renewal and annual returns for food businesses, plus trade licence, fire, pollution and other approvals your premises may need.',
    h1: 'FSSAI and the licences your business needs.',
    lead: 'Food licences and local approvals are easy to get wrong and expensive to ignore. We identify what applies to you, apply, and keep every licence renewed on time.',
    intro: [
      'Every business that makes, stores, sells or serves food in India needs registration or a licence from the Food Safety and Standards Authority of India (FSSAI), and the right type depends on your activity and size. Beyond food, premises often need local licences too.',
      'Apbiz finds out which approvals apply to your activity and premises, prepares the applications, handles queries and tracks renewals and annual returns.',
    ],
    includes: [
      ['FSSAI registration and licence', 'Basic registration, state licence or central licence, matched to your category and scale.'],
      ['Renewals and modifications', 'Renewal before expiry, and changes to address, products, owners or the type of business.'],
      ['FSSAI annual returns', 'Filing the annual return where it applies to your licence category.'],
      ['Labelling and display guidance', 'The basics of labelling, licence display and record keeping so you are inspection-ready.'],
      ['Trade and health licences', 'Municipal trade licences and similar local permissions for your premises.'],
      ['Fire, pollution and drug licences', 'Applications and renewals for the approvals that apply to your activity, where relevant.'],
      ['Notices and inspections', 'Help in replying to a department notice and preparing for an inspection.'],
    ],
    who: ['Restaurants, cloud kitchens and caterers', 'Food manufacturers, packers and traders', 'E-commerce sellers of food products', 'Shops, clinics and workshops that need local licences'],
    steps: [
      ['Find out', 'We confirm your activity, scale and premises and list the licences that apply.'],
      ['Apply', 'We collect documents, file the applications and handle departmental queries.'],
      ['Keep it valid', 'We track renewals and returns and remind you before each one is due.'],
    ],
    docs: ['PAN and Aadhaar of the owner or partners', 'Address proof and rent or ownership papers of the premises', 'Photograph and layout or plan of the premises', 'List of food products or activities', 'Incorporation or partnership documents, if any'],
    faq: [
      ['Which FSSAI licence do I need?', 'It depends on the type of food business, its turnover or production capacity and whether it operates in one or several states. We check the category and apply for the right one.'],
      ['Is a licence needed for a home kitchen?', 'Selling food, even from home, generally needs FSSAI registration or a licence depending on the scale. We confirm what applies to your case.'],
      ['What happens if my licence expires?', 'Operating without a valid licence can bring penalties, and renewing late may add a fee. We track expiry dates so you are not caught out.'],
      ['Do you handle licences in every state?', 'Most applications are made online and we work with the relevant state or central portals. If a local visit is needed, we will tell you at the start.'],
      ['Can you get other licences too?', 'Yes. Tell us what your business does and where, and we will tell you which approvals apply and what each takes.'],
    ],
    related: ['registrations', 'msme', 'gst'],
    wa: 'FSSAI and licences',
  },
  {
    slug: 'valuation', icon: 'percent', name: 'Valuation services',
    short: 'Business and share valuation for fundraising, ESOPs, share transfers, mergers and tax or regulatory needs.',
    title: 'Business and Share Valuation Services in India | Apbiz',
    desc: 'Valuation of businesses, shares and ESOPs for fundraising, share transfers, FEMA, mergers and tax purposes in India, with a clear and documented method.',
    h1: 'Valuation you can defend to investors and the tax office.',
    lead: 'A number only helps if it can be explained. We value businesses and shares with a clear method, so you can use it for fundraising, transfers, ESOPs and filings.',
    intro: [
      'Valuation is needed at many points in a company’s life: when you bring in an investor, issue or transfer shares, grant ESOPs, merge or restructure, or deal with cross-border transactions. Different situations need different methods and, in some cases, a report from a registered valuer.',
      'Apbiz prepares the analysis, explains the assumptions in plain language and coordinates with the registered valuer where the law requires one.',
    ],
    includes: [
      ['Startup and business valuation', 'Discounted cash flow, comparable and asset-based approaches, chosen to fit your stage and data.'],
      ['Share valuation for issue and transfer', 'Support for fair value reports needed under company, tax and foreign exchange rules.'],
      ['ESOP valuation', 'Fair value of the shares behind an employee stock option plan.'],
      ['Fundraising support', 'Valuation analysis and financial models for investor discussions.'],
      ['Merger and restructuring', 'Valuation and share-exchange ratio support for mergers, demergers and group restructuring.'],
      ['Intangibles and brand', 'Valuation of intellectual property and other intangible assets.'],
      ['Tax and regulatory use', 'Documentation that supports your position in tax assessments and filings.'],
    ],
    who: ['Startups raising funds from investors', 'Companies issuing or transferring shares', 'Businesses planning an ESOP', 'Promoters planning a merger, sale or restructuring'],
    steps: [
      ['Understand', 'We learn why you need the valuation and which rule or purpose it must satisfy.'],
      ['Analyse', 'We build the model from your financials and market data and explain the assumptions.'],
      ['Report', 'You receive a clear report, with the registered valuer’s sign-off where it is required.'],
    ],
    docs: ['Last three years of financial statements and the latest management accounts', 'Projections and business plan, if available', 'Shareholding pattern and cap table', 'Details of the transaction the valuation is for', 'Details of intangible assets, if relevant'],
    faq: [
      ['Do I need a registered valuer?', 'For some purposes the law requires a report from a registered valuer or a merchant banker. We tell you at the start whether yours does, and arrange it.'],
      ['Which valuation method will be used?', 'It depends on the stage of your business and what data exists. Early-stage companies are valued differently from steady, profitable ones. We explain why a method suits you.'],
      ['Can the valuation be used for an investor round?', 'Yes. Investors expect a reasoned valuation, and a documented model helps negotiations. The final price is still agreed between you and the investor.'],
      ['How long does a valuation take?', 'It depends on the purpose and how complete the data is. We give an estimate after seeing your financials.'],
      ['Is the result guaranteed to be accepted?', 'No. Authorities and investors decide for themselves. A well-documented valuation makes your case stronger.'],
    ],
    related: ['startup-india', 'company-law', 'accounting'],
    wa: 'valuation',
  },
  {
    slug: 'iso-certification', icon: 'shield', name: 'ISO and other certifications',
    short: 'ISO 9001, 14001, 45001, 27001 and 22000 certification, plus HACCP, GMP, CE and other quality marks.',
    title: 'ISO Certification: 9001, 14001, 27001, 22000 and More | Apbiz',
    desc: 'ISO 9001, 14001, 45001, 27001 and 22000 certification support, with HACCP, GMP, CE and BIS guidance, from gap check and documents to audit readiness.',
    h1: 'ISO and quality certifications, from first step to audit.',
    lead: 'Certification builds trust with customers, wins tenders and opens export doors. We prepare your documents and processes and get you ready for the certification audit.',
    intro: [
      'Many buyers, tenders and export markets ask for ISO or similar certification. The standard you need depends on what you do: quality, environment, safety, information security, food safety and so on.',
      'Apbiz explains which certification fits your goal, builds the documentation and practices the standard asks for, and coordinates with the accredited certification body for the audit.',
    ],
    includes: [
      ['ISO 9001 quality management', 'The most widely asked-for standard, for consistent quality in products and services.'],
      ['ISO 14001 and ISO 45001', 'Environmental management and occupational health and safety.'],
      ['ISO 27001 information security', 'Controls and documents for protecting data, often asked by IT and outsourcing clients.'],
      ['ISO 22000, HACCP and GMP', 'Food safety and good manufacturing practice systems for food and related businesses.'],
      ['CE, BIS and product certifications', 'Guidance on product marks needed for particular markets or product categories.'],
      ['Gap check and documentation', 'A review of where you stand today and the manuals, procedures and records you need.'],
      ['Audit preparation and follow-up', 'Training for your team, internal audits and support through surveillance audits.'],
    ],
    who: ['Manufacturers and exporters', 'IT, BPO and consulting firms', 'Food and pharma businesses', 'Contractors who need certification for tenders'],
    steps: [
      ['Choose', 'We confirm which certification your customers or tenders actually need.'],
      ['Build', 'We run a gap check, write the documents and help you put the practices in place.'],
      ['Certify', 'We coordinate the audit with an accredited certification body and close any findings.'],
    ],
    docs: ['Company registration and licences', 'Description of products, services and sites', 'Existing procedures, manuals and records, if any', 'Organisation chart and key responsibilities', 'Customer or tender requirements for certification'],
    faq: [
      ['Who issues the certificate?', 'An accredited certification body issues it after auditing you. We prepare you and coordinate, and we do not issue it ourselves.'],
      ['How long does ISO certification take?', 'It depends on the standard, the size of your business and how much is already in place. Small businesses can be ready relatively quickly. We give a plan after the gap check.'],
      ['Is the certificate valid forever?', 'No. Certificates are valid for a fixed period and are checked in regular surveillance audits. We support you through those.'],
      ['Which ISO standard should I choose?', 'It depends on your customers. Quality (9001) is the most common, while IT clients usually ask for 27001 and food businesses for 22000 or HACCP. We help you decide.'],
      ['Is it only paperwork?', 'No. An auditor checks that you actually follow the system. We build something your team can run day to day.'],
    ],
    related: ['msme', 'fssai-licences', 'registrations'],
    wa: 'ISO certification',
  },
];

export const FAQ_HOME = [
  ['What compliance does a new private limited company need?', 'Beyond incorporation, a company needs a PAN and TAN, a bank account, a GST registration if turnover or the nature of business requires it, an auditor, statutory books, and then every year its annual accounts, annual return, director KYC and income tax return. If it hires staff, PF, ESI and professional tax apply as well. We give you the list for your company.'],
  ['How do I know which GST return frequency to choose?', 'It depends on your turnover and how you prefer to cash-flow tax. Many small businesses can file quarterly; others prefer monthly. We compare the options with your actual numbers.'],
  ['What happens if I have missed filings?', 'Start by finding out exactly what is pending. Many returns can still be filed late with a fee and interest, and each additional month of delay usually costs more. We prepare a catch-up plan with the cost of each step.'],
  ['What do I need to share to get started?', 'Your PAN, the nature of your business, your registrations (GSTIN, TAN and so on), and the services you need. We will ask only for what the work requires.'],
  ['Can you work with me if I am in another city?', 'Most compliance work is done online. We use WhatsApp, email and calls, and the government portals themselves are online. For work that needs a local office visit, we will tell you before we begin.'],
  ['Will I get regular reminders?', 'Yes. We remind you before each deadline and confirm after each filing.'],
];

export const ABOUT = {
  title: 'About Apbiz: India Compliance Consultants | Apbiz',
  desc: 'Apbiz Consulting India LLP helps Indian businesses stay compliant with GST, income tax, TDS, company law and labour law, with clear communication and on-time filing.',
};

// ---- interactive elements ----

// Floating tags in the hero background: [label, depth 1 (far) to 3 (near)]. Positions are set in build.mjs.
export const HERO_TAGS = [
  ['GSTR-1', 2], ['GSTR-3B', 3], ['TDS 26Q', 2], ['Form 16', 1], ['ITR', 3], ['AOC-4', 2], ['MGT-7', 1], ['PF ECR', 3],
  ['ESI', 1], ['e-Invoice', 2], ['LUT', 1], ['DIR-3 KYC', 2], ['Udyam', 1], ['Advance tax', 3], ['FSSAI', 1], ['IEC', 2],
];

// The framed row of badges under the hero text (each gets a check seal).
export const BADGES = ['GST', 'TDS', 'ITR', 'ROC', 'PF', 'ESI', 'PT', 'MSME'];

// The two scrolling rows of "what we file".
export const MARQUEE = [
  ['GSTR-1', 'GSTR-3B', 'GSTR-9', 'E-way bills', 'E-invoicing', 'ITC reconciliation', 'GST refunds', 'LUT', 'GST notices', 'GST registration'],
  ['TDS returns', 'Form 16 and 16A', 'Income tax returns', 'Advance tax', 'AOC-4', 'MGT-7', 'DIR-3 KYC', 'LLP Form 11 and 8', 'PF and ESI returns', 'Professional tax', 'Udyam', 'FSSAI', 'Shops and Establishment', 'DPIIT recognition', 'ISO 9001', 'Business valuation', 'ESOP valuation', 'Startup India'],
];

// Tags shown in the hero of each service page.
export const SERVICE_TAGS = {
  gst: ['GSTR-1', 'GSTR-3B', 'GSTR-9', 'E-way bill', 'LUT', 'ITC', 'Refunds', 'GSTR-2B'],
  'income-tax': ['ITR', 'Advance tax', 'Tax audit', 'Capital gains', 'Form 26AS', 'Notices', 'Regime choice'],
  tds: ['24Q', '26Q', '27Q', '27EQ', 'Form 16', 'Form 16A', 'TRACES', 'TAN'],
  'company-law': ['AOC-4', 'MGT-7', 'DIR-3 KYC', 'LLP Form 8', 'LLP Form 11', 'SPICe+', 'ADT-1', 'DPT-3'],
  'pf-esi': ['PF ECR', 'ESI', 'UAN', 'PT', 'Employer code', 'Inspection', 'Claims'],
  payroll: ['Payslips', 'Salary structure', 'Form 16', 'Bonus', 'Gratuity', 'F&F', 'Bank file'],
  registrations: ['Udyam', 'FSSAI', 'IEC', 'PAN', 'TAN', 'Shops Act', 'Trade licence'],
  accounting: ['Bookkeeping', 'Bank reco', 'P&L', 'Balance sheet', 'MIS', 'Audit support'],
  'startup-india': ['DPIIT', 'Startup India', '80-IAC', 'Angel tax', 'Cap table', 'Pitch', 'Incorporation'],
  msme: ['Udyam', 'Subsidy', 'Priority loans', 'Tenders', 'Late payment', 'Schemes'],
  'fssai-licences': ['FSSAI', 'Renewal', 'Annual return', 'Trade licence', 'Fire NOC', 'Drug licence', 'Labelling'],
  valuation: ['DCF', 'Share valuation', 'ESOP', 'Fundraising', 'Merger', 'Cap table', 'Registered valuer'],
  'iso-certification': ['ISO 9001', 'ISO 14001', 'ISO 27001', 'ISO 22000', 'HACCP', 'GMP', 'CE mark'],
};
